[config]
response_language = "es-ES"
ignore_files = ["*.lock", "package-lock.json", "dist/*"]

[pr_reviewer]
extra_instructions = "Por favor, verifica que todos los strings estén internacionalizados y que no haya secretos expuestos."

[github_app]
pr_commands = ["/describe", "/review", "/test",  "/analyze"] # Solo resumen y revisión básica

